# These are supported funding model platforms
github: chnirt # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: chnirt # Replace with a single Patreon username
open_collective: chnirt # Replace with a single Open Collective username
ko_fi: chnirt # Replace with a single Ko-fi username
tidelift: chnirt/nestjs-graphql-best-practice # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: "nestjs-graphql-best-practice" # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: chnirt # Replace with a single Liberapay username
issuehunt: chnirt # Replace with a single IssueHunt username
otechie: chnirt # Replace with a single Otechie username
custom: "https://chnirt.github.io/nestjs-graphql-best-practice/" # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
